SELECT * FROM [DESKTOP-2U8N1I5\MSSQLSERVER01].NORTHWIND.DBO.PRODUCTS

CREATE DATABASE ALMACENES
GO
--CAMBIO DE ESQUEMA 
--CREAR E IS PEDRO
CREATE LOGIN PEDRO WITH PASSWORD = '123'
GO
--SE LE DA ACCESO A LA BD ALMACENES 
USE ALMACENES

CREATE USER PEDRO 
WITH DEFAULT_SCHEMA = DBO
GO

SP_HELPUSER PEDRO

--DAMOS PERMISOS DE CREAR TABLAS Y VISTAS AL USUARIO PEDRO 
USE ALMACENES 
GRANT CREATE TABLE, CREATE VIEW TO PEDRO
GO
--CREAMOS EL ESQUEMA SECCION , EL PROPIETARIO ES EL USUARIO DBO
USE ALMACENES
GO
CREATE SCHEMA SECCION AUTHORIZATION DBO
GO
--CAMBIAMOS A PEDRO AL ESQUEMA SECCION
ALTER USER PEDRO WITH DEFAULT_SCHEMA = SECCION

--SE LE DA PERMISOS DE MODIFICAR EL ESQUEMA SECCION Y DBO
GRANT ALTER ON SCHEMA :: SECCION TO PEDRO
GRANT ALTER ON SCHEMA ::DBO TO PEDRO
GO
--PARA CONSULTAR ENVIOS ES NECESARIO UTILIZAR EL ESQUEMA SECCION
SELECT * FROM ENVIOSSECCION
GO
SELECT * FROM SECCION.ENVIOSSECCION
GO

SELECT * FROM ENVIOS
GO
--MARCA ERROR 
SELECT * FROM ARTICULOS 
GO
--DEBE SER 
SELECT * FROM SECCION.ARTICULOS
GO
--NECESITAMOS CAMBIAR EL ESQUEMA A LA TABLA SECCION.ARTICULOS AL ESQUEMA DBO
ALTER SCHEMA DBO TRANSFER SECCION.ARTICULOS
GO
--YA SE PUEDE 
SELECT * FROM ARTICULOS
GO
SELECT * FROM DBO.ARTICULOS
GO
SP_HELP ARTICULOS

