/*
1-PROPIEDADES DEL SERVIDOR 
2- SEGURIDAD
3-WINDOWS

CAMBIAR LA CONTRASEÑA AL LOGIN sa, ESTE SE ENCUENTRA EN LA CARPETA DE LOGINS, DENTRO DE LA CARPETA DE SEGURIDAD
*/

--EJEMPLO 1
CREATE DATABASE VENTAS
GO
USE VENTAS
GO
CREATE TABLE CLIENTES (
CTE INT PRIMARY KEY, NOMBRE VARCHAR(50), DOMIILIO VARCHAR(50))
GO
CREATE TABLE ARTICULOS(CLAVE INT PRIMARY KEY, NOMBRE CHAR(50))
GO

CREATE LOGIN mario WITH PASSWORD = '123'
MUST_CHANGE, CHECK_EXPIRATION = ON 
GO
--VALIDAR LAS CARACTERISTICAS DE MARIO 
SP_HELPLOGINS mario
GO

--CAMBIAR AL IS MARIO LA BD VENTAS COMO BD DEFAULT
alter login mario
with default_database = VENTAS
go

--darle acceso al is mario a la BD ventas
USE VENTAS
CREATE USER mario
GO


--AGREGA AL IS MARIO A LA FUNCION SECURITYADMIN
--PUEDE EJECUTAR EL COMANDO CREATE LOGIN
sp_addSRVRoleMeMber mario, SECURITYADMIN
GO
--AGREGA AL IS MARIO A LA FUNCION DBCREATOR
--PUEDE CREAR DB Y EJECUTAR RESTORE DATABASE
sp_addSRVRoleMeMber mario,DBCREATOR
GO
--AGREGA AL IS MARIO A LA FUNCION PROCESSADMIN
--PARA ELIMINAR PROCESOS CON EL COMANDO KILL
sp_addSRVRoleMeMber mario, PROCESSADMIN
GO
--AGREGA AL IS MARIO A LA FUNCION SERVERADMIN
--PUEDE EJECUTAR EL COMANDO SHUTDOWN
sp_addSRVRoleMeMber mario, SERVERADMIN
GO

--AGREGA AL IS MARIO A LA FUNCION DBCREATOR
--PUEDE CREAR DB Y EJECUTAR RESTORE DATABASE
sp_addSRVRoleMeMber mario, DBCREATOR
GO

--
sp_SRVRolePermission SECURITYADMIN
GO
--AGREGA A MARIO ALA FUNCION DB_DATAREADER
--PARA QUE PUEDA SELECCIONAR TODAS LAS TABLAS 
USE VENTAS
GO
sp_addRoleMember db_DataReader, mario
GO
--AGREGA A MARIO ALA FUNCION DB_DataWriter
--



--CLASE 15/11/2023
--ARCHIVO MARIO2

SP_DROPROLEMEMBER DB_DATAREADER, MARIO
go
SP_DROPROLEMEMBER DB_DATAWRITER,mario
go
--pueda seleccionar solamenente la tabla clientes y no articulos
USE VENTAS
GRANT SELECT ON CLIENTES(CTE,NOMBRE)TO mario
go

--pueda solamente insertar en la tabla articulos,
--no puede actualizar ni eliminar datos en dicha tabla
grant insert on articulos to mario
go

--ES NECESARIO SACAR AL USUARIO MARIO
SP_DROPROLEMEMBER DB_DDLADMIN, MARIO
GO

--PERMISOS PARA CREAR TABLAS Y SP
GRANT CREATE PROC,CREATE TABLE TO MARIO

--ES NECESARIO DARLE PERMISO PARA MODIFICAR EL ESQUEMA DBO
GRANT ALTER ON SCHEMA::DBO TO MARIO

--SI SE LE DA PERMISOS A LA FUNCIO PUBLIC DE ELIMINACION A LA TABLA ARTICULOS Y ACTUALIZAR A LA TABLA CLIENTES
--ESTOS PERMISOS SE HEREDAN A MARIO A CUALQUIER USUARIO DE LA BD
GRANT DELETE ON ARTICULOS TO PUBLIC 

GRANT UPDATE ON CLIENTES TO PUBLIC 




--CLASE 16/11/2023, INICIO DE SESION CARLOS

--DAR DE ALTA AL IS CARLOS 
CREATE LOGIN CARLOS WITH PASSWORD='123'

--DAR ACCESO AL IS CARLOS A LA BD VENTAS
USE VENTAS
CREATE USER CARLOS

--PERMISOS DE CREAR TABLA AL USUARIO CARLOS 
USE VENTAS 
GRANT CREATE TABLE TO CARLOS
GRANT ALTER ON SCHEMA::DBO TO CARLOS

--CREACION DE LA FUNCION DESARROLLO
USE VENTAS
GO
SP_ADDROLE DESARROLLO

--PERMISOS DE CREAR TABLAS A LA FUNCION DESARROLLO
USE VENTAS
GRANT CREATE TABLE TO DESARROLLO
GRANT ALTER ON SCHEMA::DBO TO DESARROLLO
GO
--AGREGAMOS A CARLOS A LA FUNCION DESARROLLO
SP_ADDROLEMEMBER DESARROLLO, CARLOS


--SE LE REVOCA EL PERMISO DE CREACION DE TABLAS A CARLOS
USE VENTAS
REVOKE CREATE TABLE TO CARLOS

--LE REGRESAMOS EL PERMISO
GRANT CREATE TABLE TO CARLOS

--CON DENY DEFINITIVAMENTE NO PODRA CREAR TABLAS
USE VENTAS 
DENY CREATE TABLE TO CARLOS
GO


SP_HELPROLEMEMBER DESARROLLO

